[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[colors.primary]

background = "#040408"
foreground = "#cfcfd4"
bright_foreground = "#e3e3e7"

[colors.cursor]

text = "#040408"
cursor = "#cfcfd4"

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
blink_interval = 400
blink_timeout = 0
unfocused_hollow = false
thickness = 0.4

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#e3e3e7"

[colors.normal]

black = "#040408"
red = "#642020"
green = "#206420"
yellow = "#646420"
blue = "#202064"
magenta = "#642064"
cyan = "#206464"
white = "#cfcfd4"

[colors.bright]

black = "#111115"
red = "#C46060"
green = "#60C460"
yellow = "#C4C460"
blue = "#6060C4"
magenta = "#C460C4"
cyan = "#60C4C4"
white = "#e3e3e7"

[colors.search.matches]

foreground = "#9d7122"
background = "#cfcfd4"

[colors.search.focused_match]

foreground = "#2d2215"
background = "#f9e9d7"

[colors.footer_bar]

background = "#2d2215"
foreground = "#f9e9d7"

[colors.hints.start]

foreground = "#2d2215"
background = "#f9e9d7"

[colors.hints.end]

foreground = "#f9e9d7"
background = "#2d2215"

[keyboard]
bindings = [
    { key = "PageUp", action = "ScrollLineUp" },
    { key = "PageDown", action = "ScrollLineDown" },
]
